num1 = float(input())
num2 = float(input())
print("{} + {} = {:.3f}".format(num1, num2, num1 + num2))
print("{} - {} = {:.3f}".format(num1, num2, num1 - num2))
print("{} * {} = {:.3f}".format(num1, num2, num1 * num2))
print("{} / {} = {:.3f}".format(num1, num2, num1 / num2))
